// src/views/Base.vue
<template>
	<div style="background-color: #f2f3f5;height: 30vh;">
		<a-button @click="() => {
			imgMark?.move([50, 0])
		}">move x +</a-button>
		<a-button @click="() => {
			imgMark?.move([-50, 0])
		}">move x -</a-button>
		<a-button @click="() => {
			imgMark?.move([0, 50])
		}">move y +</a-button>
		<a-button @click="() => {
			imgMark?.move([0, -50])
		}">move y -</a-button>

		<a-button @click="() => {
			moveSuccessive = [0, 0]
			imgMark?.startSuccessiveMove([0, 0])
		}">start move successive</a-button>

		<a-button @click="() => {
			moveSuccessive = [0, 0]
			imgMark?.endSuccessiveMove()
		}">end move successive</a-button>

		<a-button @click="() => {
			moveSuccessive[1] += 50
			imgMark?.moveSuccessive(moveSuccessive)
		}">move successive y +</a-button>

		<a-button @click="() => {
			moveSuccessive[1] -= 50
			imgMark?.moveSuccessive(moveSuccessive)
		}">move successive y -</a-button>

		<a-button @click="() => {
			moveSuccessive[0] += 50
			imgMark?.moveSuccessive(moveSuccessive)
		}">move successive x +</a-button>

		<a-button @click="() => {
			moveSuccessive[0] -= 50
			imgMark?.moveSuccessive(moveSuccessive)
		}">move successive x -</a-button>


		<a-button @click="() => {
			imgMark?.scale(-1, 'center', 'image')
		}">scale image center -</a-button>
		<a-button @click="() => {
			imgMark?.scaleTo({
				to: 'image',
				size: 'cover',
			}, [50, 50], 'image')
		}">scale to cover -</a-button>
		<p>select text</p>
	</div>
	<div class="page-base" style="height: 60vh;">
	</div>
	<div class="h-[80vh] bg-[#86909c]"></div>
</template>
<script setup lang="ts">
import { onMounted } from 'vue';
import { ArrayPoint, ImageMark } from '../../package/index';
let imgMark: ImageMark | null = null


let moveSuccessive: ArrayPoint = [0, 0]


onMounted(() => {
	imgMark = new ImageMark({
		el: '.page-base',
		src: '/2.png',
		// enableImageOutOfContainer: false,
		moveConfig: {
		},
		initScaleConfig: {
			startPosition: 'center',
			size: 'fit',
			// to: 'box',
			// box: {
			// 	x: 1270,
			// 	y: 626,
			// 	width: 20,
			// 	height: 20,
			// },
			// box: {
			// 	x: 50,
			// 	y: 50,
			// 	width: 100,
			// 	height: 100,
			// },
			// padding: 50,
			paddingUnit: 'px'
		}
	}).on('first_render', () => {
		// imgMark?.setMinScale('cover')
		// imgMark?.removeStageLmbDownMoveing()
	}).on('scale', (scale: number) => {
		console.log(scale);
	})
})
</script>
<style scoped lang="scss">
.page-base {}
</style>

// src/views/Base.tsx
import ImageMark, { ArrayPoint } from "#/index"
import { Button, Space } from "@arco-design/web-react"
import { useEffect, useRef } from "react"
import { OperateGroup } from "../components/OperateGroup"

export function Base() {
	const moveSuccessive = useRef<ArrayPoint>([0, 0])
	let imgMark = useRef<InstanceType<typeof ImageMark> | null>(null)
	const containerRef = useRef<HTMLDivElement>(null)
	useEffect(() => {
		if (!containerRef.current) throw new Error("containerRef is null")
		imgMark.current = new ImageMark({
			el: containerRef.current,
			src: '/2.png',
			moveConfig: {},
			initScaleConfig: {
				startPosition: 'center',
				size: 'fit',
				// to: 'box',
				// box: {
				// 	x: 1270,
				// 	y: 626,
				// 	width: 20,
				// 	height: 20,
				// },
				// box: {
				// 	x: 50,
				// 	y: 50,
				// 	width: 100,
				// 	height: 100,
				// },
				// padding: 50,
				paddingUnit: 'px'
			}
		}).on('first_render', () => {
			// imgMark?.setMinScale('cover')
			// imgMark?.removeStageLmbDownMoveing()
		}).on('scale', (scale: number) => {
			console.log(scale);
		})
	}, [])

	function onMoveSuccessive() {
		imgMark.current?.moveSuccessive(moveSuccessive.current)
	}

	return (
		<div className="page-base">
			<div className="operate-panel h-[fit] py-[16px]">
				<Space size={'large'}>
					<OperateGroup desc="移动画布">
						<Button.Group>
							<Button onClick={() => {
								imgMark.current?.move([50, 0])
							}}>x+</Button>
							<Button onClick={() => {
								imgMark.current?.move([-50, 0])
							}}>x-</Button>
							<Button onClick={() => {
								imgMark.current?.move([0, 50])
							}}>y+</Button>
							<Button onClick={() => {
								imgMark.current?.move([0, -50])
							}}>y-</Button>
						</Button.Group>
					</OperateGroup>
					<OperateGroup desc="连续移动画布：会记录第一个点，然后根据后边的点算新的位置，适合鼠标拖动移动场景">
						<Button.Group>
							<Button onClick={() => {
								moveSuccessive.current = [0, 0]
								imgMark.current?.removeStageLmbDownMoveing()
								imgMark.current?.startSuccessiveMove([0, 0])
							}}>Move Start</Button>
							<Button onClick={() => {
								moveSuccessive.current[0] += 50
								onMoveSuccessive()
							}}>x+</Button>
							<Button onClick={() => {
								moveSuccessive.current[0] -= 50
								onMoveSuccessive()
							}}>x-</Button>
							<Button onClick={() => {
								moveSuccessive.current[1] += 50
								onMoveSuccessive()
							}}>y+</Button>
							<Button onClick={() => {
								moveSuccessive.current[1] -= 50
								onMoveSuccessive()
							}}>y-</Button>
							<Button onClick={() => {
								moveSuccessive.current = [0, 0]
								imgMark.current?.endSuccessiveMove()
								imgMark.current?.addStageLmbDownMoveing()
							}}>Move End</Button>
						</Button.Group>
					</OperateGroup>
					<OperateGroup desc="缩放画布">
						<Button.Group >
							<Button onClick={() => {
								imgMark.current?.scale(-1, 'center', 'image')
							}}>Img Center-</Button>
							<Button onClick={() => {
								imgMark.current?.scaleTo({
									to: 'image',
									size: 'cover'
								}, 'center', 'image')
							}}>Scale To Cover</Button>
						</Button.Group>

					</OperateGroup>
				</Space>
			</div>
			<div className="h-[60vh]" ref={containerRef}>
			</div>
			<div className="h-[80vh] bg-[#86909c]"></div>
		</div>
	)
}
